version: '3.8'

services:
  nginx:
    image: docker.arvancloud.ir/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./legacy-php:/var/www/legacy
      - ./laravel-api:/var/www/laravel
    depends_on:
      - php
      - laravel
    networks:
      - appnet

  php:
    # image: docker.arvancloud.ir/php:8.2-fpm
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./legacy-php:/var/www/legacy
    networks:
      - appnet

  laravel:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./laravel-api:/var/www/laravel
    networks:
      - appnet

  mysql:
    image: docker.arvancloud.ir/mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shared_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
        image: docker.arvancloud.ir/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - appnet
        depends_on:
            - mysql

networks:
  appnet:
    driver: bridge

volumes:
  mysql-data:
